### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [mkoehnke/WKZombie#21] opened 2016-04-02 06:40 UTC
Hi,
It's will be great to add [Carthage](https://github.com/Carthage/Carthage) support

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods] (http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

**Comment by mkoehnke** [comment] 2016-04-02 16:37
Hi, thank you for the article links! Carthage is definitely something I want to support. To do this, it might be necessary to create a new project for the WKZombie files itself. I'll look into it.

**Comment by Dershowitz011** [comment] 2016-04-04 06:22
@mkoehnke I'd happily do it for you. If you don't mind.

**Comment by mkoehnke** [comment] 2016-04-04 07:03
@Dershowitz011 Thanks for your offer. Sure. Just make a pull request with a short description of what you've changed. Thanks!

**Comment by Dershowitz011** [comment] 2016-04-04 07:05
There's really nothing to change @mkoehnke . Just add all the classes you've made already to a framework and share it. That's all. But I am not getting how to import hpple. :disappointed:

**Comment by mkoehnke** [comment] 2016-04-04 07:12
@Dershowitz011 As a dependency of WKZombie, does hpple have to support Carthage as well? Because it currently doesn't.

**Comment by Dershowitz011** [comment] 2016-04-04 07:16
No it doesn't need Carthage support. If your framework has it as a dependency, it's enough!

**Comment by mkoehnke** [comment] 2016-04-08 15:33
Implemented with pull request #25

**Comment by antoine-ki** [comment] 2016-06-05 10:23
Hi,
The hpple framework dependency is causing an issue:
`Could not pick a version for github "mkoehnke/hpple", due to mutually incompatible requirements:
	"31e334f56953d8ff38c4d36910ea364d4f465fa6"
	"master"`

I cant install WKZombie using carthage. 

Help
Thank you 💃

**Comment by mkoehnke** [comment] 2016-06-06 06:25
Hi @antoine-ki. Thanks for trying out WKZombie! Unfortunately, I can't reproduce the issue you're seeing. Could you please be more specific about the content of your `Cartfile` and your `carthage` parameters.

**Comment by antoine-ki** [comment] 2016-06-06 06:29
Hi, Sure,

Cartfile Content:
`github "mkoehnke/WKZombie"`

Cartfile update:
`carthage update --platform iOS`

I have a Regular Carthage installation

When i run the update command i get:
`*** Fetching WKZombie
*** Fetching hpple
Could not pick a version for github "mkoehnke/hpple", due to mutually incompatible requirements:
	"31e334f56953d8ff38c4d36910ea364d4f465fa6"
	"master"`

**Comment by mkoehnke** [comment] 2016-06-06 06:59
@antoine-ki Strange. Please try to add a tag number to your Cartfile
`github "mkoehnke/WKZombie" "0.9.5"`

and run carthage again:
`carthage update --no-use-binaries --platform iOS`

**Comment by antoine-ki** [comment] 2016-06-06 07:03
It Worked! 

I added the version number to the Cartfile.
Didn't add --no-use-binaries

Can you tell me why the error was occurring?

Thank you 👯

**Comment by mkoehnke** [comment] 2016-06-06 07:17
@antoine-ki It looks like that Carthage doesn't work that well if a framework dependency (hpple) is referenced via branch name. Using a tag seems to be the way to go. I've created a new WKZombie version (0.9.5) that does that. As Carthage always uses the latest tag by default, `github "mkoehnke/WKZombie"`should work now as well. Could you please try that with your setup?

**Comment by antoine-ki** [comment] 2016-06-06 08:25
Worked! Thank you.

Side question: (i dont want to open an issue for it)
Lets say i want to get the content of an input that i filled

I do:
`        browser.open(NSURL(string: "https://www.google.com")!)
        >>> browser.get(by: .Name("q"))
        >>> browser.setAttribute("value", value: "test")
        >>> browser.get(by: .Name("q"))`

then `=== testRes

function testRes(){}`

What should the input of the function be? HTMLElement? I tried it it gives me an error

**Comment by mkoehnke** [comment] 2016-06-06 21:26
@antoine-ki I would like to avoid mixing issues / questions. Feel free to open a new issue anytime. Even if it's just a question.

Anyway. Regarding your question. Your code should look something like this:
```swift
    browser.open(NSURL(string: "https://www.google.com")!) 
>>> browser.get(by: .Name("q")) 
>>> browser.setAttribute("value", value: "test")
>>> browser.get(by: .Name("q"))
=== testRes
```
```swift
func testRes(result: HTMLElement?) {
  // handle result
}
```
or 
```swift
func testRes(result: Result<HTMLElement>) {
  switch result {
  case .Success(let value): // handle success
  case .Error(let error): // handle error
  }
}
```

Let me know if that helps and I can close this issue.

Thanks.

**Closed** 2016-06-08 15:09 UTC
Labels: enhancement
